const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('traderAPI', {
  snapshot: () => ipcRenderer.invoke('app:snapshot'),
  saveSettings: value => ipcRenderer.invoke('settings:save', value),
  savePartialFill: value => ipcRenderer.invoke('settings:partialFill', value),
  saveRiskSettings: value => ipcRenderer.invoke('settings:risk', value),
  saveNewsFeeds: value => ipcRenderer.invoke('settings:news-feeds', value),
  saveApiKey: value => ipcRenderer.invoke('secrets:saveKey', value),
  loadMarket: query => ipcRenderer.invoke('market:load', query),
  loadDepth: query => ipcRenderer.invoke('market:depth', query),
  loadInstrument: symbol => ipcRenderer.invoke('market:instrument', symbol),
  onPaperState: callback => ipcRenderer.on('paper:state', (_event, data) => callback(data)),
  subscribeMarket: symbols => ipcRenderer.invoke('market:subscribe', symbols),
  onMarketTick: callback => ipcRenderer.on('market:tick', (_event, data) => callback(data)),
  onAutomationUpdate: callback => ipcRenderer.on('automation:update', (_event, data) => callback(data)),
  onAutomationProgress: callback => ipcRenderer.on('automation:progress', (_event, data) => callback(data)),
  onPaperAlert: callback => ipcRenderer.on('paper:alert', (_event, data) => callback(data)),
  onBrokerUpdate: callback => ipcRenderer.on('broker:update', (_event, data) => callback(data)),
  refreshPaper: () => ipcRenderer.invoke('paper:refresh'),
  resetPaper: amount => ipcRenderer.invoke('paper:reset', amount),
  listPaperBackups: () => ipcRenderer.invoke('paper:listBackups'),
  restorePaperBackup: () => ipcRenderer.invoke('paper:restoreBackup'),
  verifyPaper: () => ipcRenderer.invoke('paper:verify'),
  pausePaper: () => ipcRenderer.invoke('paper:pause'),
  resumePaper: () => ipcRenderer.invoke('paper:resume'),
  killPaper: () => ipcRenderer.invoke('paper:kill'),
  runPaperAutomation: () => ipcRenderer.invoke('paper:automation-start').then(result => result?.state || result),
  startPaperAutomation: () => ipcRenderer.invoke('paper:automation-start'),
  stopPaperAutomation: () => ipcRenderer.invoke('paper:automation-stop'),
  cancelPaper: orderId => ipcRenderer.invoke('paper:cancel', orderId),
  exportPaper: () => ipcRenderer.invoke('paper:export'),
  exportPaperCsv: () => ipcRenderer.invoke('paper:exportCsv'),
  runBacktest: query => ipcRenderer.invoke('research:backtest', query),
  compareBacktests: query => ipcRenderer.invoke('research:compare', query),
  evaluateAgents: () => ipcRenderer.invoke('research:evaluate-agents'),
  researchReport: () => ipcRenderer.invoke('research:report'),
  listExperiments: () => ipcRenderer.invoke('research:experiments'),
  saveBrokerCredentials: value => ipcRenderer.invoke('broker:saveCredentials', value),
  brokerPreflight: () => ipcRenderer.invoke('broker:preflight'),
  reconcileBroker: () => ipcRenderer.invoke('broker:reconcile'),
  brokerSnapshot: () => ipcRenderer.invoke('broker:snapshot'),
  selectBrokerAccount: value => ipcRenderer.invoke('broker:select', value),
  armLiveSession: value => ipcRenderer.invoke('broker:arm', value),
  disarmLiveSession: value => ipcRenderer.invoke('broker:disarm', value),
  previewLiveOrder: value => ipcRenderer.invoke('broker:preview', value),
  submitLiveOrder: value => ipcRenderer.invoke('broker:submit', value),
  cancelLiveOrder: value => ipcRenderer.invoke('broker:cancel', value),
  killLiveSession: value => ipcRenderer.invoke('broker:kill', value),
  exportLiveReport: () => ipcRenderer.invoke('broker:report'),
  analyze: query => ipcRenderer.invoke('llm:analyze', query),
  executePaper: order => ipcRenderer.invoke('paper:execute', order),
  openData: () => ipcRenderer.invoke('app:openData')
});
