const realMoney=value=>new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(Number(value)||0);
const realEscape=value=>esc(String(value??''));
const realOpenStatus=new Set(['accepted','partial','cancelling','unknown']);

window.renderRealWorkspace=function renderRealWorkspace(){
  if(window.realSessionTimer)clearInterval(window.realSessionTimer);
  const b=snapshot.broker||{},accounts=b.accounts||[],selected=accounts.find(a=>a.id===b.activeId),limits=b.limits||{},sandbox=b.environment==='testnet'||b.environment==='demo';
  $('#page').innerHTML=`
    <section class="real-banner"><span class="real-banner-icon">R</span><div><strong>Trading spot con Binance</strong><p>Conexión directa · claves cifradas localmente · sin retiros</p></div><span class="real-env">${realEscape(b.environment||'SIN CUENTA')}</span></section>
    <section class="card real-card"><div class="real-heading"><div><p class="section-kicker">CUENTA Y ENTORNO</p><h2>Conexión del broker</h2><p>La cuenta, las órdenes y el historial de esta vista permanecen separados del paper.</p></div><span class="real-connection ${b.status==='connected'?'connected':b.status==='attention'?'attention':''}"><i></i>${b.status==='connected'?'Conectada':b.status==='attention'?'Revisión requerida':b.status==='error'?'Desconectada':'Sin verificar'}</span></div>
    ${accounts.length?`<div class="field"><label for="realAccountSelect">Cuenta guardada</label><select id="realAccountSelect">${accounts.map(a=>`<option value="${realEscape(a.id)}" ${a.id===b.activeId?'selected':''}>${realEscape(a.label)} · ${realEscape(a.environment)}</option>`).join('')}</select></div>`:''}
    <div class="real-connect-grid"><div class="field"><label for="brokerEnvironment">Entorno Binance</label><select id="brokerEnvironment"><option value="testnet">Spot Testnet · saldo de prueba</option><option value="demo">Spot Demo · saldo de prueba</option><option value="mainnet">Mainnet · saldo real</option></select></div><div class="field"><label for="brokerLabel">Nombre local de la cuenta</label><input id="brokerLabel" maxlength="60" placeholder="Ej. Demo de Binance"></div><div class="field"><label for="brokerApiKey">API key del broker</label><input id="brokerApiKey" type="password" autocomplete="off" spellcheck="false" placeholder="Se cifra en este dispositivo"></div><div class="field"><label for="brokerSecret">Secret del broker</label><input id="brokerSecret" type="password" autocomplete="new-password" spellcheck="false" placeholder="Solo se usa en el proceso principal"></div></div>
    <div class="real-actions"><button class="btn primary" id="saveBroker">Guardar y conectar</button><button class="btn" id="refreshBroker">Sincronizar cuenta</button><button class="btn" id="livePreflight">Preflight</button><span id="brokerActionStatus" class="subtle"></span></div>
    <p class="real-key-note">La clave solo puede leerse al crearla en Binance. Para real, activa únicamente lectura y trading spot; desactiva retiros y restringe por IP.</p></section>
    <section class="real-columns"><div class="card real-card"><div class="real-heading"><div><p class="section-kicker">ESTADO DE CUENTA</p><h2>Preflight de operación</h2></div><span class="real-sync">${b.lastSyncAt?`Sincronizada ${time(b.lastSyncAt)}`:'Cuenta pendiente de sincronización'}</span></div><div id="realPreflightBody">${renderRealPreflight(b)}</div><div id="realBalanceBody">${renderRealBalances(b.account?.balances||[])}</div></div>
    <div class="card real-card real-arm-card"><div class="real-heading"><div><p class="section-kicker">ACTIVACIÓN TEMPORAL</p><h2>Sesión manual</h2></div><span class="session-chip ${b.armed?'armed':''}">${b.armed?`ACTIVA · ${time(b.armedUntil)}`:'DESARMADA'}</span></div><p class="real-copy">Cada orden requiere revisión individual. Las llamadas del LLM y Auto-Paper nunca envían órdenes a esta cuenta.</p>
    <div class="risk-fields"><div class="field"><label for="liveQuoteAsset">Moneda de límites</label><select id="liveQuoteAsset"><option value="USDT">USDT</option><option value="USDC">USDC</option></select></div><div class="field"><label for="liveSymbols">Símbolos permitidos</label><input id="liveSymbols" value="${realEscape((limits.symbols||['BTCUSDT','ETHUSDT','SOLUSDT']).join(', '))}"></div><div class="field"><label for="liveMaxOrder">Máximo por orden (USDT)</label><input id="liveMaxOrder" type="number" min="1" max="10000" value="${Number(limits.maxOrderNotional)||25}"></div><div class="field"><label for="liveDailyBuy">Máximo compras por día (USDT)</label><input id="liveDailyBuy" type="number" min="1" max="100000" value="${Number(limits.maxDailyBuyNotional)||100}"></div><div class="field"><label for="liveMaxAsset">Exposición máxima por activo (%)</label><input id="liveMaxAsset" type="number" min="1" max="100" value="${Number(limits.maxAssetExposurePct)||35}"></div><div class="field"><label for="liveMaxTotal">Exposición máxima total (%)</label><input id="liveMaxTotal" type="number" min="1" max="100" value="${Number(limits.maxTotalExposurePct)||75}"></div><div class="field"><label for="liveMaxDailyLoss">Pérdida diaria máxima (%)</label><input id="liveMaxDailyLoss" type="number" min="1" max="100" value="${Number(limits.maxDailyLossPct)||3}"></div><div class="field"><label for="liveMaxDrawdown">Drawdown máximo (%)</label><input id="liveMaxDrawdown" type="number" min="1" max="100" value="${Number(limits.maxDrawdownPct)||10}"></div></div>
    <label class="real-consent"><input type="checkbox" id="confirmRealRisk"><span>Entiendo que un fill real puede perder dinero y que debo vigilar el equipo y el mercado.</span></label><label class="real-consent"><input type="checkbox" id="confirmRealLimits"><span>He comprobado los límites, permisos spot y restricción de IP de esta cuenta.</span></label><div class="field real-arm-phrase"><label for="realArmPhrase">Escribe exactamente <code id="expectedArmPhrase">${realEscape(b.acknowledgement||'Conecta y sincroniza la cuenta')}</code></label><input id="realArmPhrase" autocomplete="off" spellcheck="false"></div>
    <div class="real-actions"><button class="btn primary" id="armRealSession">${b.armed?'Renovar 15 min':'Activar sesión · 15 min'}</button><button class="btn danger" id="disarmRealSession" ${b.armed?'':'disabled'}>Desarmar</button><button class="btn danger" id="killRealSession">Kill switch</button></div><p class="real-key-note">Kill switch desarma y cancela las órdenes de esta app; no liquida posiciones. Si el estado remoto queda incierto, detén la sesión y resuelve la orden en Binance.</p></div></section>
    ${sandbox?renderSandboxOrderForm():''}
    <section class="card real-card"><div class="real-heading"><div><p class="section-kicker">ORDEN MANUAL</p><h2>Revisar y enviar una orden</h2><p>Spot, sin apalancamiento · precio, filtros, saldo y límites vuelven a comprobarse antes del envío.</p></div><span class="real-env ${b.armed?'armed':''}">${b.armed?'SESIÓN ARMADA':'SESIÓN DESARMADA'}</span></div><div class="real-order-form"><div class="field"><label for="liveOrderSymbol">Símbolo</label><input id="liveOrderSymbol" value="${realEscape((limits.symbols||['BTCUSDT'])[0])}" autocomplete="off"></div><div class="field"><label for="liveOrderSide">Lado</label><select id="liveOrderSide"><option value="BUY">BUY · comprar</option><option value="SELL">SELL · vender</option></select></div><div class="field"><label for="liveOrderType">Tipo</label><select id="liveOrderType"><option value="LIMIT">LIMIT · precio máximo/mínimo</option><option value="MARKET">MARKET · precio actual</option></select></div><div class="field real-limit-price"><label for="liveOrderPrice">Precio límite</label><input id="liveOrderPrice" type="number" min="0" step="any" placeholder="Cotización actual"></div><div class="field"><label for="liveOrderQuantity">Cantidad</label><input id="liveOrderQuantity" type="number" min="0" step="any" placeholder="Respeta lote mínimo"></div><div class="field real-preview-action"><label>&nbsp;</label><button class="btn primary" id="previewRealOrder" ${b.armed?'':'disabled'}>Revisar orden</button></div></div><div id="liveOrderPreview" aria-live="polite"></div><div id="realOrdersBody">${renderRealOrders(b.orders||[])}</div></section>`;
  const select=$('#brokerEnvironment');select.value=['testnet','demo','mainnet'].includes(b.environment)?b.environment:'testnet';
  if($('#liveQuoteAsset'))$('#liveQuoteAsset').value=limits.quoteAsset||'USDT';
  $('#realAccountSelect')?.addEventListener('change',async e=>{await realAction('Cambiando de cuenta…',async()=>{snapshot.broker=await window.traderAPI.selectBrokerAccount({id:e.target.value});render();});});
  $('#brokerEnvironment').onchange=()=>{$('#brokerActionStatus').textContent=$('#brokerEnvironment').value==='mainnet'?'MAINNET: la confirmación y los límites serán obligatorios.':'Entorno de pruebas; la sesión seguirá desarmada.';};
  $('#saveBroker').onclick=()=>realAction('Cifrando y conectando…',async()=>{snapshot.broker=await window.traderAPI.saveBrokerCredentials({environment:select.value,label:$('#brokerLabel').value,apiKey:$('#brokerApiKey').value,secret:$('#brokerSecret').value});$('#brokerApiKey').value='';$('#brokerSecret').value='';render();});
  $('#refreshBroker').onclick=()=>realAction('Reconciliando cuenta, órdenes y fills…',async()=>{snapshot.broker=await window.traderAPI.reconcileBroker();render();});
  $('#testBroker')?.remove();
  $('#livePreflight').onclick=()=>realAction('Evaluando cuenta y permisos…',async()=>{$('#realPreflightBody').innerHTML=renderRealChecks(await window.traderAPI.brokerPreflight());snapshot.broker=await window.traderAPI.brokerSnapshot();updateRealSummary(snapshot.broker);});
  $('#armRealSession').onclick=()=>realAction('Sincronizando y evaluando límites…',async()=>{const value={scope:b.scope,limits:{quoteAsset:$('#liveQuoteAsset').value,symbols:$('#liveSymbols').value.split(',').map(s=>s.trim()),maxOrderNotional:$('#liveMaxOrder').value,maxDailyBuyNotional:$('#liveDailyBuy').value,maxAssetExposurePct:$('#liveMaxAsset').value,maxTotalExposurePct:$('#liveMaxTotal').value,maxDailyLossPct:$('#liveMaxDailyLoss').value,maxDrawdownPct:$('#liveMaxDrawdown').value},acknowledgement:$('#realArmPhrase').value,confirmRisk:$('#confirmRealRisk').checked,confirmLocalMonitoring:$('#confirmRealLimits').checked};snapshot.broker=await window.traderAPI.armLiveSession(value);render();toast('Sesión activada durante 15 minutos.');});
  $('#disarmRealSession').onclick=()=>realAction('Desarmando…',async()=>{snapshot.broker=await window.traderAPI.disarmLiveSession({scope:b.scope});render();});
  $('#killRealSession').onclick=async()=>{const okay=confirm('Se desarmará la sesión y se cancelarán las órdenes abiertas creadas por esta app. No se cerrarán las posiciones. ¿Continuar?');if(!okay)return;await realAction('Deteniendo, consultando y cancelando…',async()=>{const result=await window.traderAPI.killLiveSession({scope:b.scope});snapshot.broker=result.snapshot;render();toast(result.complete?'Kill switch completado; no quedan órdenes abiertas de esta app.':'Kill switch parcial: quedan estados inciertos. No envíes otra orden hasta reconciliar.');});};
  const syncType=()=>{$('.real-limit-price').hidden=$('#liveOrderType').value==='MARKET';$('#previewRealOrder').textContent='Revisar orden';};$('#liveOrderType').onchange=syncType;syncType();
  $('#previewRealOrder').onclick=()=>previewRealOrder(b.scope);
  bindLiveWorkspaceEvents();
  window.realSessionTimer=setInterval(()=>{
    if(typeof page!=='undefined'&&page==='live'&&window.traderAPI?.brokerSnapshot){
      window.traderAPI.brokerSnapshot().then(fresh=>{snapshot.broker=fresh;const chip=document.querySelector('.session-chip');if(chip){chip.textContent=fresh.armed?`ACTIVA · ${time(fresh.armedUntil)}`:'DESARMADA';chip.classList.toggle('armed',fresh.armed);}const preview=document.querySelector('#previewRealOrder');if(preview)preview.disabled=!fresh.armed;const phrase=document.querySelector('#expectedArmPhrase');if(phrase)phrase.textContent=fresh.acknowledgement||'Conecta y sincroniza la cuenta';}).catch(()=>{});
    }
  },1000);
};

function renderRealPreflight(b){if(b.status==='error')return `<div class="real-error">${realEscape(b.error||'No se pudo conectar. Revisa red, hora y permisos.')}</div>`;if(!b.status||b.status==='not-connected')return '<p class="real-copy">Conecta una cuenta sandbox y sincroniza para revisar este checklist. Mainnet empieza desarmado.</p>';return renderRealChecks({checks:[{label:'Cuenta sincronizada',ok:b.status==='connected'||b.status==='attention',detail:b.lastSyncAt||'Sin lectura válida'},{label:'Sesión explícita',ok:b.armed,detail:b.armed?`Armada hasta ${time(b.armedUntil)}`:'No armada'},{label:'Ordenes sin confirmar',ok:!b.pendingCommands,detail:b.pendingCommands?`${b.pendingCommands} comando(s) por reconciliar`:'Sin órdenes con estado desconocido'},{label:'Órdenes remotas',ok:!b.recovery?.length,detail:b.recovery?.length?`${b.recovery.length} incidencias pendientes`:'Sin incidencias de recuperación'}]});}
function renderRealChecks(report){return `<div class="real-check-list">${(report?.checks||[]).map(c=>`<div class="real-check ${c.ok?'ok':'fail'}"><i></i><strong>${realEscape(c.label)}</strong><span>${realEscape(c.detail)}</span></div>`).join('')}</div>`;}
function renderRealBalances(items){if(!items?.length)return '<p class="real-copy">Sin balances con saldo para mostrar.</p>';return `<div class="real-table-wrap"><table class="table real-table"><thead><tr><th>ACTIVO</th><th>LIBRE</th><th>EN ÓRDENES</th><th>TOTAL</th></tr></thead><tbody>${items.slice(0,50).map(x=>`<tr><td><strong>${realEscape(x.asset)}</strong></td><td>${realMoney(x.free)}</td><td>${realMoney(x.locked)}</td><td>${realMoney(x.total)}</td></tr>`).join('')}</tbody></table></div>`;}
function renderRealOrders(orders){if(!orders?.length)return '<p class="real-copy">No hay órdenes de este espacio.</p>';return `<div class="real-table-wrap"><table class="table real-table"><thead><tr><th>SÍMBOLO</th><th>LADO</th><th>ESTADO</th><th>LLENADO</th><th>ACCIÓN</th></tr></thead><tbody>${orders.slice(-100).reverse().map(o=>`<tr><td>${realEscape(o.symbol)}</td><td>${realEscape(o.side)}</td><td><span class="real-order-state ${o.status==='filled'?'ok':''}">${realEscape(o.status)}</span></td><td>${realMoney(o.executedQuantity)} / ${realMoney(o.quantity)}</td><td>${realOpenStatus.has(o.status)&&o.clientOrderId?`<button class="table-action" data-live-cancel="${realEscape(o.symbol)}" data-client-order-id="${realEscape(o.clientOrderId)}" data-scope="${realEscape(snapshot.broker.scope)}">Cancelar</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`;}
function renderSandboxOrderForm(){return `<section class="card real-card sandbox-info"><p class="section-kicker">SALDOS VIRTUALES DEL PROVEEDOR</p><h2>Sandbox y Demo usan saldo de prueba</h2><p>Spot Testnet o Demo permiten ejercitar el contrato de orden sin fondos de mainnet. Las órdenes de prueba se listan y cancelan en la tabla de esta cuenta.</p></section>`;}
function updateRealSummary(b){$('#realPreflightBody').innerHTML=renderRealPreflight(b);$('#realBalanceBody').innerHTML=renderRealBalances(b.account?.balances||[]);$('#realOrdersBody').innerHTML=renderRealOrders(b.orders||[]);}
async function realAction(label,action){const target=$('#brokerActionStatus');if(target)target.textContent=label;try{await action();if(target)target.textContent='Listo';}catch(error){if(target)target.textContent='';toast(error.message);}}
async function previewRealOrder(scope){
  const button=$('#previewRealOrder');button.disabled=true;$('#liveOrderPreview').innerHTML='<p class="real-copy">Revalidando cotización, instrumento, saldo y riesgo…</p>';
  try{
    const preview=await window.traderAPI.previewLiveOrder({scope,symbol:$('#liveOrderSymbol').value,side:$('#liveOrderSide').value,type:$('#liveOrderType').value,quantity:Number($('#liveOrderQuantity').value),price:Number($('#liveOrderPrice').value)||undefined});
    const p=preview.order,r=preview.risk,isMain=preview.environment==='mainnet';
    $('#liveOrderPreview').innerHTML=`<div class="order-review"><div class="real-heading"><div><p class="section-kicker">REVISIÓN · ${realEscape(preview.environment.toUpperCase())}</p><strong>${realEscape(p.side)} ${realEscape(p.quantity)} ${realEscape(p.symbol)}</strong></div><span class="review-expiry">Vence en 30 s</span></div><div class="review-facts"><span>Tipo<strong>${realEscape(p.type)}</strong></span><span>${p.price?'Precio límite':'Precio actual'}<strong>${p.price?realMoney(p.price):realMoney(r.referencePrice)} ${realEscape(r.quoteAsset)}</strong></span><span>Nocional estimado<strong>${realMoney(r.notional)} ${realEscape(r.quoteAsset)}</strong></span><span>Spread<strong>${Number(r.spreadBps).toFixed(2)} bps</strong></span><span>Protección por comisión<strong>${r.feeBufferPct}% de margen</strong></span><span>Cuenta<strong>${realEscape(preview.environment)}</strong></span></div>${isMain?`<label class="real-order-ack"><input id="confirmRealOrder" type="checkbox"><span>Confirmo enviar esta orden a <strong>MAINNET</strong>. Puede ejecutarse y usar saldo real.</span></label>`:`<label class="real-order-ack"><input id="confirmSandboxOrder" type="checkbox"><span>Confirmo una orden en saldo virtual ${realEscape(preview.environment.toUpperCase())}.</span></label>`}<div class="real-submit-row"><div class="field"><label for="confirmOrderPhrase">Escribe <code>${realEscape(preview.acknowledgement)}</code></label><input id="confirmOrderPhrase" autocomplete="off"></div><button class="btn ${isMain?'real-danger':'primary'}" id="confirmLiveOrder" disabled>${isMain?'ENVIAR ORDEN REAL':'Enviar orden sandbox'}</button></div><button type="button" class="report-button" id="discardLiveReview">Descartar revisión</button></div>`;
    const accepted=$('#confirmLiveOrder'),check=$('#confirmRealOrder')||$('#confirmSandboxOrder'),phrase=$('#confirmOrderPhrase');const update=()=>{accepted.disabled=!check.checked||phrase.value.trim()!==preview.acknowledgement;};check.onchange=update;phrase.oninput=update;
    accepted.onclick=async()=>{accepted.disabled=true;accepted.textContent='Enviando…';try{const result=await window.traderAPI.submitLiveOrder({scope,previewId:preview.id,requestId:preview.requestId,acknowledgement:preview.acknowledgement});snapshot.broker=result.snapshot;$('#liveOrderPreview').innerHTML=result.command?`<div class="order-result"><strong>${realEscape(result.command.status)}</strong><span>${realEscape(result.command.order.symbol)} · ${realEscape(result.command.order.side)} · ID ${realEscape(result.command.clientOrderId)}</span><small>${result.command.status==='unknown'?'Estado sin confirmar. Reconciliando; no se enviará otra orden.':`Saldo real y fills se consultaron de nuevo en Binance.`}</small></div>`:`<p class="real-copy">${realEscape(result.command?.status||'Orden recibida; pendiente de reconciliación.')}</p>`;updateRealSummary(snapshot.broker);if($('#liveOrderQuantity'))$('#liveOrderQuantity').value='';}
      catch(error){$('#liveOrderPreview').insertAdjacentHTML('beforeend',`<div class="real-error">${realEscape(error.message)}</div>`);accepted.textContent=isMain?'REINTENTAR NO DISPONIBLE':'Reconciliar sandbox';toast(error.message);}
    };
    $('#discardLiveReview').onclick=()=>{$('#liveOrderPreview').replaceChildren();button.disabled=!snapshot.broker?.armed;};
  }catch(error){$('#liveOrderPreview').innerHTML=`<div class="real-error">${realEscape(error.message)}</div>`;toast(error.message);}
  finally{if($('#previewRealOrder'))$('#previewRealOrder').disabled=!snapshot.broker?.armed;}
}
function bindLiveWorkspaceEvents(){
  $$('[data-live-cancel]').forEach(button=>button.onclick=async()=>{if(!confirm(`¿Cancelar la orden ${button.dataset.clientOrderId} en Binance ${snapshot.broker.environment}?`))return;button.disabled=true;try{snapshot.broker=await window.traderAPI.cancelLiveOrder({scope:button.dataset.scope,symbol:button.dataset.liveCancel,clientOrderId:button.dataset.clientOrderId});updateRealSummary(snapshot.broker);}catch(error){toast(error.message);}});
}
window.updateBrokerStatus=broker=>{snapshot.broker=broker;if(typeof page!=='undefined'&&page==='live')updateRealSummary(broker);};
